id: IBB797B8B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T10:15:33+00:00'
last_modified: '2022-06-08T01:10:30.347121+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9603
  title: ན་ལེནྡྲའི་བསྐང་གསོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D3FB:
      image_group_id: I1KG9629
      title: ''
      total_pages: 332
      order: 1
      base_file: D3FB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
